### ISSUE TITLE
too many certificates already issued for this exact set of domains

### ISSUE THREAD

**Issue by vcmirko** [therootcompany/greenlock-express.js#12]
my greenlock.d/config.json file is updated correctly (root + correct access)
```

{
  "sites": [
    {
      "subject": "mydomain.com",
      "altnames": [
        "mydomain.com"
      ],
      "renewAt": 1
    }
  ],
  "defaults": {
    "store": {
      "module": "greenlock-store-fs"
    },
    "challenges": {
      "http-01": {
        "module": "acme-http-01-standalone"
      }
    },
    "renewOffset": "-45d",
    "renewStagger": "3d",
    "accountKeyType": "EC-P256",
    "serverKeyType": "RSA-2048",
    "subscriberEmail": "myname@domain.com"
  }
}
```

But still each time at start, it tries to renew the certificates, hitting the rate limit.

```
0|greenloc | By using this software you (myname@domain.com) are agreeing to the following:
0|greenloc | ACME Subscriber Agreement: https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf
0|greenloc | Greenlock/ACME.js Terms of Use: https://rootprojects.org/legal/#terms
0|greenloc |
0|greenloc | set greenlockOptions.notify to override the default logger
0|greenloc | certificate_order (more info available: account subject altnames challengeTypes)
0|greenloc | certificate_order (more info available: account subject altnames challengeTypes)
0|greenloc | certificate_order (more info available: account subject altnames challengeTypes)
0|greenloc | certificate_order (more info available: account subject altnames challengeTypes)
0|greenloc | certificate_order (more info available: account subject altnames challengeTypes)
0|greenloc | certificate_order (more info available: account subject altnames challengeTypes)
0|greenloc | Listening on 0.0.0.0:80 for ACME challenges, and redirecting to HTTPS
0|greenloc | Listening on 0.0.0.0:443 for secure traffic
0|greenloc | Ready to Serve:
0|greenloc |     mydomain.com

0|greenlock-app  | ACME Directory URL: https://acme-v02.api.letsencrypt.org/directory
0|greenlock-app  | By using this software you (myname@domain.com) are agreeing to the following:
0|greenlock-app  | ACME Subscriber Agreement: https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf
0|greenlock-app  | Greenlock/ACME.js Terms of Use: https://rootprojects.org/legal/#terms
0|greenlock-app  | set greenlockOptions.notify to override the default logger
0|greenlock-app  | certificate_order (more info available: account subject altnames challengeTypes)
0|greenlock-app  | Error cert_issue:
0|greenlock-app  | [acme-v2.js] authorizations were not fetched for 'mydomain.com':
0|greenlock-app  | {"type":"urn:ietf:params:acme:error:rateLimited","detail":"Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: mydomain.com, retry after 2022-10-08T17:26:38Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/","status":429,"_identifiers":[{"type":"dns","value":"mydomain.com"}]}
0|greenlock-app  | Error: [acme-v2.js] authorizations were not fetched for 'mydomain.com':
0|greenlock-app  | {"type":"urn:ietf:params:acme:error:rateLimited","detail":"Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: mydomain.com, retry after 2022-10-08T17:26:38Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/","status":429,"_identifiers":[{"type":"dns","value":"mydomain.com"}]}
0|greenlock-app  |     at Object.E.NO_AUTHORIZATIONS (/srv/apps/portal/server/node_modules/@root/acme/errors.js:75:9)
0|greenlock-app  |     at /srv/apps/portal/server/node_modules/@root/acme/acme.js:1198:11
0|greenlock-app  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|greenlock-app  | Error cert_issue:
0|greenlock-app  | [acme-v2.js] authorizations were not fetched for 'mydomain.com':
0|greenlock-app  | {"type":"urn:ietf:params:acme:error:rateLimited","detail":"Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: mydomain.com, retry after 2022-10-08T17:26:38Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/","status":429,"_identifiers":[{"type":"dns","value":"mydomain.com"}]}
0|greenlock-app  | Error: [acme-v2.js] authorizations were not fetched for 'mydomain.com':
0|greenlock-app  | {"type":"urn:ietf:params:acme:error:rateLimited","detail":"Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: mydomain.com, retry after 2022-10-08T17:26:38Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/","status":429,"_identifiers":[{"type":"dns","value":"mydomain.com"}]}
0|greenlock-app  |     at Object.E.NO_AUTHORIZATIONS (/srv/apps/portal/server/node_modules/@root/acme/errors.js:75:9)
0|greenlock-app  |     at /srv/apps/portal/server/node_modules/@root/acme/acme.js:1198:11
0|greenlock-app  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|greenlock-app  | Error cert_issue:
0|greenlock-app  | [acme-v2.js] authorizations wer
```

**Comment by vcmirko** [comment]
For future reference, for other people having the same issue.
I was using the default config from the examples, which is basically a sub directory.  With every build, the config was reset and thus issueing a new certificate, hitting the limit.

So I have moved the `greenlock.d` directory outside my build, in the parent folder  
  
My new config is now this (note the configDir is referencing the parent path) : 

```
  const path = require("path")
  var configDir = path.join(__dirname,"./../greenlock.d")
  console.log(`greenlock config => ${configDir}`)
  require("greenlock-express")
      .init({
          packageRoot: "./",
          configDir: configDir,

          // contact for security and critical bug notices
          maintainerEmail: "mymail@domain.com",

          // whether or not to run at cloudscale
          cluster: false
      })
      // Serves on 80 and 443
      // Get's SSL certificates magically!
      .serve(app);
```
My `greenlock.d` folder is now persistent and not getting reset by new builds.
